# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20171028_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpagegalleryimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='blogpagegalleryimage',
            name='page',
        ),
        migrations.DeleteModel(
            name='BlogPageGalleryImage',
        ),
    ]
