# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('blog', '0016_auto_20171029_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.wagtailcore.fields.StreamField((('content', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow')), ('code', wagtail.wagtailcore.blocks.StructBlock((('language', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('javascript', 'Javascript'), ('python', 'Python'), ('html', 'HTML'), ('css', 'CSS'), ('c', 'C')])), ('code', wagtail.wagtailcore.blocks.RawHTMLBlock())), icon='code')), ('raw_code', wagtail.wagtailcore.blocks.StructBlock((('code', wagtail.wagtailcore.blocks.RawHTMLBlock()),), icon='placeholder')), ('image', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('caption', wagtail.wagtailcore.blocks.RichTextBlock(max_length=255, required=False))), icon='image'))))),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
