# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('blog', '0017_contentpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='ContentPage',
        ),
    ]
