# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 08:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20171114_0812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='categories',
            new_name='category',
        ),
    ]
