# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 06:47
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='links',
            field=wagtail.wagtailcore.fields.StreamField((('links', wagtail.wagtailcore.blocks.StructBlock((('link', wagtail.wagtailcore.blocks.PageChooserBlock(required=True)), ('text', wagtail.wagtailcore.blocks.CharBlock(max_length=255))), blank=True, null=True)),), null=True),
        ),
    ]
